apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: configmap-deploy-start-slack
spec:
  params:
  - name: taskRunName
    description: The name of the TaskRun
  - name: taskRunNamespace
    description: The namespace of the TaskRun
  - name: dashboardBaseURL
    description: The base URL of the Tekton dashboard
  - name: gitResource
    description: The git sha of the deployed resource
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: TaskRun
    metadata:
      name: send-to-webhook-slack-$(uid)
    spec:
      taskRef:
        name: send-to-webhook-slack
      params:
        - name: webhook-secret
          value: robocat-slack-app-webhook
        - name: message
          value: >-
            :boom: The TaskRun <On $(tt.params.taskRunNamespace)/taskruns/$(tt.params.taskRunName)|$(tt.params.taskRunNamespace)/$(tt.params.taskRunName)>
            failed to deploy